name: Tag and Publish (devpi)

on:
  push:
    branches:
      - $default-branch
      - 'dev'

jobs: 
  # Auto bump version and Tag
  tag: 
    uses: AllenNeuralDynamics/.github/.github/workflows/release-tag-uv-python.yml@dev # TODO: change to main after testing

  # Publish to devpi on eng-tools
  publish: 
    needs: tag
    uses: AllenNeuralDynamics/.github/.github/workflows/release-pkg-devpi-python.yml@dev # TODO: change to main after testing
    secrets: inherit