name: Tag and Publish (eng-tools release)

on: 
  push: 
    branches: 
      - $default-branch
      - 'dev'

jobs: 
  # Auto bump version and Tag
  tag: 
    uses: AllenNeuralDynamics/.github/workflows/tag.yml@main
    with: 
      runner_label: self-hosted-good
    secrets: inherit

  # Publish to eng-tools/release
  publish: 
    needs: tag
    uses: AllenNeuralDynamics/.github/workflows/publish_executable.yml@main
    with: 
      runner_label: self-hosted-good
    secrets: inherit