name: Tag and Publish (devpi)

on:
  push:
    branches:
      - $default-branch
      - 'dev'

jobs: 
  # Auto bump version and Tag
  tag: 
    uses: AllenNeuralDynamics/.github/.github/workflows/tag.yml@main
    with: 
      runner_label: eng-tools
    secrets: inherit

  # Publish to devpi on eng-tools
  publish: 
    needs: tag
    uses: AllenNeuralDynamics/.github/.github/workflows/publish_devpi.yml@main
    with: 
      runner_label: eng-tools
    secrets: inherit