name: Tag and Publish
on:
  push:
    branches:
      - $default-branch
      - dev

jobs: 
  # Auto bump version and Tag
  tag: 
    uses: AllenNeuralDynamics/github-workflows/.github/workflows/tag.yml@main
    with: 
      runner_label: self-hosted-good
    secrets: inherit

  # Publish to devpi on eng-tools
  publish: 
    needs: tag
    uses: AllenNeuralDynamics/github-workflows/.github/workflows/publish_devpi.yml@main
    with: 
      runner_label: self-hosted-good
    secrets: inherit