name: Type Lint and Test Python

on: 
  pull_request: 
    branches: 
      - [ $default-branch, $default-branch-2 ]
    types: [opened, synchronize, reopened, ready_for_review]

env: 
  # Define runner for all the jobs
  runner_label: 'windows-latest'

jobs: 
  # Lint check and Type check ran in parallel
  lint_check:
      uses: AllenNeuralDynamics/.github/workflows/lint.yml@main
      with: 
        runner_type: ${{ env.runner_label }}
  type_check:
      uses: AllenNeuralDynamics/.github/workflows/type.yml@main
      with: 
        runner_type: ${{ env.runner_label }}

  # Run unit tests if lint and type check passes
  tests:
    needs: [lint_check, type_check]
    uses: AllenNeuralDynamics/.github/workflows/type.yml@main
    with: 
      runner_type: ${{ env.runner_label }}
  
