name: Build and Create exe Release

on:
  workflow_call:
    inputs: 
      runner_label: 
        description: 'Runner to use'
        type: string
        default: 'eng-tools'
      zip_name:
        description: 'Name of zip file'
        type: string
      project_name:
        description: 'Name of executable'
        type: string

env: 
  ZIP_NAME: ${{ inputs.zip_name }}          # if not set, it will be extracted from setup.py or pyproject.toml
  PROJECT_NAME: ${{ inputs.project_name }}  # if not set, it will be extracted from setup.py or pyproject.toml

jobs:
  build: 
    runs-on: ${{ inputs.runner_label }}
    outputs:
      project-name: ${{ needs.extract-info.outputs.project-name }}
      project-version: ${{ needs.extract-info.outputs.project-version }}
    env: 
      UV_PYTHON_INSTALL_DIR: C:\ProgramData\AIBS_MPE\uv_python
      UV_TOOL_DIR: C:\ProgramData\AIBS_MPE\uv_python
    steps:
      - name: Run extract_info only if PROJECT_NAME is not set
        # TODO: update to main after testing...
        uses: AllenNeuralDynamics/.github/.github/actions/extract_info@dev
        id: extract_info
        if: env.PROJECT_NAME == ''
      - name: Set PROJECT_NAME from extract_info (if not already set)
        id: set_project_name
        shell: bash
        run: |
          PROJECT_NAME="${PROJECT_NAME:-${{ steps.extract_info.outputs.project-name }}}"
          echo "PROJECT_NAME=$PROJECT_NAME" >> "$GITHUB_ENV"
      - name: Set ZIP_NAME from extract_info (if not already set)
        id: set_zip_name
        shell: bash
        run: |
          ZIP_NAME="${ZIP_NAME:-${{ steps.extract_info.outputs.project-name }}}"
          echo "ZIP_NAME=$ZIP_NAME" >> "$GITHUB_ENV"
      
      - name: Clean before build (Windows)
        if: runner.os == 'Windows'
        run: |
          Remove-Item -Recurse -Force build,dist,__pycache__,$env:PROJECT_NAME.exe,$env:ZIP_NAME.zip
      - name: Clean before build (Linux/MacOS)
        if: runner.os != 'Windows'
        run: |
          rm -rf build dist __pycache__ *.spec ${{ env.ZIP_NAME }}.zip

      - name: Install UV 
        uses: astral-sh/setup-uv@v5
      - name: Sync dependencies
        run: uv sync
      - name: Install pyinstaller
        run: uv add pyinstaller
      - name: Build Project with PyInstaller
        run: uv run pyinstaller --name ${{ env.PROJECT_NAME }} src/jessy-test/main.py # replace this with the path to your script

      - name: Create zip on Windows
        if: runner.os == 'Windows'
        shell: powershell
        run: Compress-Archive -Path dist/* -DestinationPath "${{ env.ZIP_NAME }}.zip"
      - name: Create zip on Linux/macOS
        if: runner.os != 'Windows'
        run: zip -r "${{ env.ZIP_NAME }}.zip" dist/

