name: Create Github/eng-tools release

on:
  workflow_call:
    inputs: 
      runner-label: 
        description: 'Runner to use'
        type: string
        default: 'eng-tools'
      project-name: 
        description: 'Project name (used to make eng-tools/release directory)'
        type: string
      project-version: 
        description: 'Project version (used to make eng-tools/release subdirectory)'
        type: string
      files: 
        description: 'List of files/directories to upload to release'
        type: string
      tag-name: 
        description: 'Tag to upload files to (defaults to latest)'
        type: string

jobs:
  ################################################################################
  #
  #   Release to Github Releases
  #
  ################################################################################
  publish: 
    runs-on: ${{ inputs.runner-label }}
    steps: 
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ input.files }}
          tag_name: ${{ inputs.tag-name }} 
          body: "Automated release of ${{ project-name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  ################################################################################
  #
  #   Release to eng-tools/release
  #   Go to http://eng-tools/gh-pull-agent/docs for more information on API
  #
  ################################################################################
  call-api:
    runs-on: ${{ inputs.runner-label }}
    needs: publish
    steps: 
      - name: Trigger gh-pull-agent to pull latest release from this repo to eng-tools
        shell: bash
        run: |
          project_name = '${{ inputs.project-name }}'
          project_version = '${{ inputs.project-version }}'
          owner_name = '"${{ github.repository_owner }}"'
          repo_name = '"${{ github.event.repository.name }}"'
          $json = @{
            '"owner_name"' = $owner_name
            '"repo_name"' = $repo_name
          } | ConvertTo-Json -Compress
          & curl.exe -X PUT "http://eng-tools/gh-pull-agent/api/v1beta/releases/$project_name/$project_version" `
            -H "accept: application/json" `
            -H "Content-Type: application/json" `
            -d $json