name: test (pytest)

on:
  workflow_call:
    inputs: 
      runner_label: 
        description: 'Runner to use'
        type: string
        default: 'ubuntu-latest'

jobs: 
  run-tests: 
    runs-on: ${{ inputs.runner_label }}
    steps: 
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install UV 
      uses: astral-sh/setup-uv@v5
    - name: Unit test with PyTest  
      run: uv run pytest tests/