name: Type (mypy)

on:
  workflow_call:
    inputs: 
      runner_label: 
        description: 'Runner to use'
        type: string
        default: 'ubuntu-latest'
      mypy-commands: 
        description: 'mypy commands to run'
        required: true
        type: string

jobs: 
  type_check: 
    runs-on: ${{ inputs.runner_label }}
    steps: 
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install UV 
      uses: astral-sh/setup-uv@v5
    - name: Type check with mypy 
      run: |
        uv run mypy ${{ inputs.mypy-commands }}