name: Type (mypy)

on:
  workflow_call:
    inputs: 
      runner_label: 
        description: 'Runner to use'
        type: string
        default: 'ubuntu-latest'

jobs: 
  type_check: 
    runs-on: ${{ inputs.runner_label }}
    steps: 
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install UV 
      uses: astral-sh/setup-uv@v5
    - name: Type check with mypy 
      run: |
        uv run mypy src/mypackage --strict